# test of travis
language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - gcc
      - flex
      - bison
      - build-essential
      - etoolbox
      - poppler-utils
      - texlive
      - texlive-latex-extra
      - python3
      - python3-ply
      - python3-numpy
      - python3-yaml
before_install:
  - sudo dpkg-reconfigure dash
  - cmake -version
script:
  - ./build_debs_mcstas 2.3
  - sudo dpkg -i dist/mcstas-2.3-linux64.deb
  # - sudo dpkg -i dist/mcstas-tools-perl-2.3-linux64.deb
  - sudo dpkg -i dist/mcstas-tools-perl-cmdline-2.3-linux64.deb
  # - sudo dpkg -i dist/mcstas-tools-matlab-mcplot-2.3-linux64.deb
  # - sudo dpkg -i dist/mcstas-tools-python-mcplot-pyqtgraph-2.3-linux64.de
  - sudo dpkg -i dist/mcstas-tools-python-mcrun-2.3-linux64.deb
  # - sudo dpkg -i dist/mcstas-tools-python-mcgui-2.3-linux64.deb
  - sudo dpkg -i dist/mcstas-tools-python-mccodelib-2.3-linux64.deb
  #- sudo dpkg -i dist/mcstas-tools-python-mcdisplay-webgl-2.3-linux64.deb
  #- sudo dpkg -i dist/mcstas-tools-python-mcdisplay-pyqtgraph-2.3-linux64.deb
  #- sudo dpkg -i dist/mcstas-tools-python-mcdisplay-mantid-2.3-linux64.deb
  - sudo dpkg -i dist/mcstas-manuals-2.3-linux64.deb
  - sudo apt-get install -f
  # - sudo dpkg -i dist/mcstas-tools-perl-2.3-linux64.deb
  - mcrun --test
  

