# test of travis
language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - gcc
      - flex
      - bison
      - build-essential
      - etoolbox
      - poppler-utils
      - texlive
      - texlive-latex-extra
before_install:
  - sudo dpkg-reconfigure dash
  - cmake -version
script:
  - ./build_debs_mcstas 2.3

